/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from '@elegant-router/types';

// 懒加载布局组件以提升性能
export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: () => import('@/layouts/base-layout/index.vue'),
  blank: () => import('@/layouts/blank-layout/index.vue')
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import('@/views/_builtin/403/index.vue'),
  404: () => import('@/views/_builtin/404/index.vue'),
  500: () => import('@/views/_builtin/500/index.vue'),
  'iframe-page': () => import('@/views/_builtin/iframe-page/[url].vue'),
  'login': () => import('@/views/_builtin/login'),
  'chat': () => import('@/views/chat/index.tsx'),
  'component': () => import('@/views/component/index'),
  'file-manager': () => import('@/views/file-manager/index'),
  'file-manager-documents': () => import('@/views/file-manager/documents/index'),
  'home': () => import('@/views/home/index'),
  'markdownedit': () => import('@/views/markdownEdit/index'),
  'menu-management': () => import('@/views/menu-management/index'),
  'mobile': () => import('@/views/mobile/index.vue'),
  'upload': () => import('@/views/upload/index'),
  'utils': () => import('@/views/utils/index.vue'),
  'monitoring': () => import('@/views/monitoring/index'),
  'user-management': () => import('@/views/user-management/index'),
  'role-management': () => import('@/views/role-management/index'),
  'permission-management': () => import('@/views/permission-management/index'),
  'announcement-management': () => import('@/views/announcement-management/index'),
  'notification-management': () => import('@/views/notification-management/index'),
  'alert-management': () => import('@/views/alert-management/index'),
  'log-management': () => import('@/views/log-management/index'),
  'version-log-management': () => import('@/views/version-log-management/index'),
  'ai-workflow': () => import('@/views/ai-workflow/index'),
  'ai-workflow-editor': () => import('@/views/ai-workflow/editor/index'),
  'agent-management': () => import('@/views/agent-management/index'),
  'agent-management-editor': () => import('@/views/agent-management/editor/index'),
  'model-profile-management': () => import('@/views/model-profile-management/index'),
  'agent-team-management': () => import('@/views/agent-team-management/index'),
  'agent-runtime': () => import('@/views/agent-runtime/index')
};
