/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'chat',
    path: '/chat',
    component: 'layout.base$view.chat',
    meta: {
      title: 'chat',
      i18nKey: 'route.chat',
      icon: 'mdi:chat',
      order: 2
    }
  },
  {
    name: 'component',
    path: '/component',
    component: 'layout.base$view.component',
    meta: {
      title: 'component',
      i18nKey: 'route.component'
    }
  },
  {
    name: 'file-manager',
    path: '/file-manager',
    component: 'layout.base$view.file-manager',
    meta: {
      title: 'file-manager',
      i18nKey: 'route.file-manager',
      icon: 'mdi:book-open-page-variant',
      order: 3
    }
  },
  {
    name: 'file-manager-documents',
    path: '/file-manager/:kbId',
    component: 'layout.base$view.file-manager-documents',
    props: true,
    meta: {
      title: 'file-manager-documents',
      i18nKey: 'route.file-manager-documents',
      hideInMenu: true,
      activeMenu: 'file-manager'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:home-outline',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'markdownedit',
    path: '/markdownedit',
    component: 'layout.base$view.markdownedit',
    meta: {
      title: 'markdownedit',
      i18nKey: 'route.markdownedit',
      icon: 'mdi:markdown',
      order: 2
    }
  },
  {
    name: 'menu-management',
    path: '/menu-management',
    component: 'layout.base$view.menu-management',
    meta: {
      title: 'menu-management',
      i18nKey: 'route.menu-management',
      icon: 'mdi:menu',
      order: 6
    }
  },
  {
    name: 'mobile',
    path: '/mobile',
    component: 'layout.base$view.mobile',
    meta: {
      title: 'mobile',
      i18nKey: 'route.mobile'
    }
  },
  {
    name: 'upload',
    path: '/upload',
    component: 'layout.base$view.upload',
    meta: {
      title: 'upload',
      i18nKey: 'route.upload',
      icon: 'mdi:upload-multiple'
    }
  },
  {
    name: 'utils',
    path: '/utils',
    component: 'layout.base$view.utils',
    meta: {
      title: 'utils',
      i18nKey: 'route.utils'
    }
  },
  {
    name: 'monitoring',
    path: '/monitoring',
    component: 'layout.base$view.monitoring',
    meta: {
      title: 'monitoring',
      i18nKey: 'route.monitoring',
      icon: 'mdi:monitor-dashboard',
      order: 4
    }
  },
  {
    name: 'user-management',
    path: '/user-management',
    component: 'layout.base$view.user-management',
    meta: {
      title: 'user-management',
      i18nKey: 'route.user-management',
      icon: 'mdi:account-group',
      order: 4
    }
  },
  {
    name: 'role-management',
    path: '/role-management',
    component: 'layout.base$view.role-management',
    meta: {
      title: 'role-management',
      i18nKey: 'route.role-management',
      icon: 'mdi:account-key',
      order: 5
    }
  },
  {
    name: 'permission-management',
    path: '/permission-management',
    component: 'layout.base$view.permission-management',
    meta: {
      title: 'permission-management',
      i18nKey: 'route.permission-management',
      icon: 'mdi:shield-key',
      order: 6
    }
  },
  {
    name: 'announcement-management',
    path: '/announcement-management',
    component: 'layout.base$view.announcement-management',
    meta: {
      title: 'announcement-management',
      i18nKey: 'route.announcement-management',
      icon: 'mdi:bullhorn',
      order: 7
    }
  },
  {
    name: 'notification-management',
    path: '/notification-management',
    component: 'layout.base$view.notification-management',
    meta: {
      title: 'notification-management',
      i18nKey: 'route.notification-management',
      icon: 'mdi:bell',
      order: 8
    }
  },
  {
    name: 'alert-management',
    path: '/alert-management',
    component: 'layout.base$view.alert-management',
    meta: {
      title: 'alert-management',
      i18nKey: 'route.alert-management',
      icon: 'mdi:alert',
      order: 9
    }
  },
  {
    name: 'log-management',
    path: '/log-management',
    component: 'layout.base$view.log-management',
    meta: {
      title: 'log-management',
      i18nKey: 'route.log-management',
      icon: 'mdi:file-document-outline',
      order: 10
    }
  },
  {
    name: 'version-log-management',
    path: '/version-log-management',
    component: 'layout.base$view.version-log-management',
    meta: {
      title: 'version-log-management',
      i18nKey: 'route.version-log-management',
      icon: 'mdi:history',
      order: 11
    }
  },
  {
    name: 'ai-workflow',
    path: '/ai-workflow',
    component: 'layout.base$view.ai-workflow',
    meta: {
      title: 'ai-workflow',
      i18nKey: 'route.ai-workflow',
      icon: 'mdi:workflow',
      order: 2
    }
  },
  {
    name: 'ai-workflow-editor',
    path: '/ai-workflow/editor/:id',
    component: 'layout.base$view.ai-workflow-editor',
    props: true,
    meta: {
      title: 'ai-workflow-editor',
      i18nKey: 'route.ai-workflow-editor',
      hideInMenu: true,
      activeMenu: 'ai-workflow'
    }
  }
];
